version: '3.9'
services:
  mysql-cont:
    image: mysql:latest #Pulling the image from docker hub
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/libmysql
  
  frontend-cont:
    build: .
    image: m51-pet-img:latest
    environment:
      SPRING_URL: ${SPRING_URL}
      SPRING_USERNAME: ${SPRING_USERNAME}
      SPRING_PASSWORD: ${SPRINGPASSWORD}
    depends_on:
      - mysql-cont
    ports:
      - "${SERVER_PORT}:8080"

volumes: #volume creationS
  mysql-data:
